// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXtL5qi_5UHYFzr_XmF7lFiSex-dXp718',
    appId: '1:768675648628:web:db77371fb4f146a1ebad21',
    messagingSenderId: '768675648628',
    projectId: 'swipefit-3cf0d',
    authDomain: 'swipefit-3cf0d.firebaseapp.com',
    storageBucket: 'swipefit-3cf0d.firebasestorage.app',
    measurementId: 'G-5GKBP2VV6G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0f5zDNQhExyJ6Ure5vsn6LEuvmW5fQJk',
    appId: '1:768675648628:android:1978024ce97da6d6ebad21',
    messagingSenderId: '768675648628',
    projectId: 'swipefit-3cf0d',
    storageBucket: 'swipefit-3cf0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByZtlH8L2kJAGeBKWWk3BA-llie1CnJ7U',
    appId: '1:768675648628:ios:da1821805f4f3852ebad21',
    messagingSenderId: '768675648628',
    projectId: 'swipefit-3cf0d',
    storageBucket: 'swipefit-3cf0d.firebasestorage.app',
    iosBundleId: 'com.example.swipefit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByZtlH8L2kJAGeBKWWk3BA-llie1CnJ7U',
    appId: '1:768675648628:ios:da1821805f4f3852ebad21',
    messagingSenderId: '768675648628',
    projectId: 'swipefit-3cf0d',
    storageBucket: 'swipefit-3cf0d.firebasestorage.app',
    iosBundleId: 'com.example.swipefit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXtL5qi_5UHYFzr_XmF7lFiSex-dXp718',
    appId: '1:768675648628:web:f92ef4bc0b305b2debad21',
    messagingSenderId: '768675648628',
    projectId: 'swipefit-3cf0d',
    authDomain: 'swipefit-3cf0d.firebaseapp.com',
    storageBucket: 'swipefit-3cf0d.firebasestorage.app',
    measurementId: 'G-MEH36JS7P2',
  );

}